name: Deploy

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Install dependencies
        run: composer install --no-scripts --no-interaction

      - name: Build
        run: php bin/console cache:clear --env=prod

      - name: 📂 SFTP uploader
        uses: wangyucode/sftp-upload-action@v2.0.2
        with:
          host: ${{ secrets.SERVER }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          localDir: "./"
          remoteDir: "/home/mmi21g05/public_html/api-movies-app/"