name: Deploy

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Deploy symfony app
        uses: appleboy/ssh-action@master
        with:
            HOST: ${{ secrets.HOST }}
            USERNAME: ${{ secrets.USERNAME }}
            PORT: ${{ secrets.PORT }}
            KEY: ${{ secrets.SSHKEY }}
            script: |
              cd public_html/
              git clone git@github.com:killian-dv/symfony-s5.git tmp_symfony_s5
              mv tmp_symfony_s5 api-movies-app
              cd api-movies-app
              git pull
              composer install
              php bin/console c:c