name: Deploy

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Install dependencies
        run: composer install --no-scripts --no-interaction

      - name: Build
        run: php bin/console cache:clear --env=dev

      - name: 📂 SFTP uploader
        uses: wangyucode/sftp-upload-action@v2.0.2
        with:
          host: ${{ secrets.SERVER }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          localDir: "./"
          remoteDir: "./public_html/api-movies-app/"

      - name: connect to db
        uses: appleboy/ssh-action@master
        with:
            HOST: ${{ secrets.HOST }}
            USERNAME: ${{ secrets.USERNAME }}
            PORT: ${{ secrets.PORT }}
            KEY: ${{ secrets.SSHKEY }}
            script: |
              cd public_html/api-movies-app/
              echo "Deployment successful!"